# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab0da11d0bb1f2a9328f753afb4ac8003f7207d93354d6c9270197f33f15a93dab53c5af804e9eba609ef3f2dfdff388584901fcfc91ff4abe670963184c2b8f

test:
  secret_key_base: e4561d8c847cd456a2dfbdd0cadfc3cd4be2fe4ed679542ce5e85cef7ead7de99cf45f4ff62eb7f659bb138d0596f58e7aab56c4d7b3966e1c9d6c514db4ec25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
